HealthNet/HealthNet/urls.py
from django.conf.urls import include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = (
    # Examples:

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('health.urls', namespace='health'))
)

HealthNet/health/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from . import views

# Make sure to end each URL pattern with '/?$' to make sure the end of the url
# properly handles omitting the trailing slash.
urlpatterns = (
    url(r'login/?$', views.login_view, name='login'),
    url(r'logout/?$', views.logout_view, name='logout'),
    url(r'schedule/?$', views.schedule, name='schedule'),
    url(r'prescriptions/?$', views.prescriptions, name='prescriptions'),
    url(r'messages/?$', views.messages, name='messages'),
    url(r'messages/(\d+)/?$', views.conversation, name='conversation'),
    url(r'delete_prescription/(\d+)/?$', views.delete_prescription, name='delete_prescription'),
    url(r'edit_prescription/(\d+)?/?$', views.prescription_form, name='edit_prescription'),
    url(r'add_prescription/?$', views.add_prescription_form, name='add_prescription'),
    url(r'delete_appointment/(\d+)/?$', views.delete_appointment, name='delete_appointment'),
    url(r'edit_appointment/(\d+)?/?$', views.appointment_form, name='edit_appointment'),
    url(r'add_appointment/?$', views.add_appointment_form, name='add_appointment'),
    url(r'add_group/?$', views.add_group, name='add_group'),
    url(r'users/(\d+)/?$', views.medical_information, name='medical_information'),
    url(r'users/me/?$', views.my_medical_information, name='my_medical_information'),
    url(r'signup/?$', views.signup, name='signup'),
    url(r'users/(\d+)/info.json/?$', views.export, name='export'),
    url(r'users/me/info.json/?$', views.export_me, name='export_me'),
    url(r'users/?$', views.users, name='users'),
    url(r'logs/?$', views.logs, name='logs'),
    url(r'^/?$', views.home, name='home'),
)

HealthNet/health/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import dateparse
from django.core.exceptions import PermissionDenied
from django.contrib.admin.models import LogEntry
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse
from django.db.models import Max
from . import form_utilities
from .form_utilities import *
from . import checks
from .models import *
import datetime
import json
import time


def login_view(request):
    """
    Presents a simple form for logging in a user.
    If requested via POST, looks for the username and password,
    and attempts to log the user in. If the credentials are invalid,
    it passes an error message to the context which the template will
    render using a Bootstrap alert.

    :param request: The Django request object.
    :return: The rendered 'login' page.
    """
    context = {'navbar':'login'}
    if request.POST:
        user, message = login_user_from_form(request, request.POST)
        if user:
            return redirect('health:home')
        elif message:
            context['error_message'] = message
    return render(request, 'login.html', context)


def login_user_from_form(request, body):
    """
    Validates a user's login credentials and returns a tuple
    containing either a valid, logged-in user or a failure
    message.

    Checks if all fields were supplied, then attempts to authenticate,
    then checks if the 'remember' checkbox was checked. If it was, sets
    the cookie's expiration to 0, meaning it will be invalidated when the
    session ends.

    :param request: The Django request object.
    :return: The rendered 'login' page.
    """
    email = body.get("email")
    password = body.get("password")
    if not all([email, password]):
        return None, "You must provide an email and password."
    email = email.lower()  # all emails are lowercase in the database.
    user = authenticate(username=email, password=password)
    remember = body.get("remember")
    if user is None:
        return None, "Invalid username or password."
    login(request, user)
    if remember is not None:
        request.session.set_expiry(0)
    return user, None


def logout_view(request):
    """
    Logs the user out and redirects the user to the login page.
    :param request: The Django request.
    :return: A 301 redirect to the login page.
    """
    logout(request)
    return redirect('health:login')


def handle_prescription_form(request, body, prescription=None):
    name = body.get("name")
    dosage = body.get("dosage")
    patient = body.get("patient")
    directions = body.get("directions")
    if not all([name, dosage, patient, directions]):
        return None, "All fields are required."
    try:
        patient = User.objects.get(pk=int(patient))
    except ValueError:
        return None, "We could not find the user specified."

    if prescription:
        changed_fields = []
        if prescription.name != name:
            changed_fields.append('name')
            prescription.name = name
        if prescription.dosage != dosage:
            changed_fields.append('dosage')
            prescription.dosage = dosage
        if prescription.directions != directions:
            changed_fields.append('directions')
            prescription.directions = directions
        if prescription.patient != patient:
            changed_fields.append('patient')
            prescription.patient = patient
        prescription.save()
        change(request, prescription, changed_fields)
    else:
        prescription = Prescription.objects.create(name=name, dosage=dosage,
                                        patient=patient, directions=directions,
                                        prescribed=timezone.now(), active=True)

        if not prescription:
            return None, "We could not create that prescription. Please try again."
        addition(request, prescription)
    return prescription, None


@login_required
def prescriptions(request, error=None):
    """
    Renders a table of the prescriptions associated with this user.

    :param request: The Django request.
    :return: A rendered version of prescriptions.html
    """
    context = {
        "navbar":"prescriptions",
        "logged_in_user": request.user,
        "prescriptions": request.user.prescription_set.filter(active=True).all()
    }
    if error:
        context["error_message"] = error

    return render(request, 'prescriptions.html', context)


def add_prescription_form(request):
    return prescription_form(request, None)


def prescription_form(request, prescription_id):
    prescription = None
    if prescription_id:
        prescription = get_object_or_404(Prescription, pk=prescription_id)
    if request.POST:
        if not request.user.can_add_prescription():
            raise PermissionDenied
        p, message = handle_prescription_form(request, request.POST, prescription)
        return prescriptions(request, error=message)
    context = {
        'prescription': prescription,
        'logged_in_user': request.user
    }
    return render(request, 'edit_prescription.html', context)


def delete_prescription(request, prescription_id):
    p = get_object_or_404(Prescription, pk=prescription_id)
    p.active = False
    p.save()
    deletion(request, p, repr(p))
    return redirect('health:prescriptions')


def signup(request):
    """
    Presents a simple signup page with a form of all the required
    fields for new users.
    Uses the full_signup_context function to populate a year/month/day picker
    and, if the user was created successfully, prompts the user to log in.
    :param request:
    :return:
    """
    context = full_signup_context(None)
    context['is_signup'] = True
    if request.POST:
        user, message = handle_user_form(request, request.POST)
        if user:
            addition(request, user)
            if request.user.is_authenticated():
                return redirect('health:signup')
            else:
                return redirect('health:login')
        elif message:
            context['error_message'] = message
    context['navbar'] = 'signup'
    return render(request, 'signup.html', context)


def full_signup_context(user):
    """
    Returns a dictionary containing valid years, months, days, hospitals,
    and groups in the database.
    """
    return {
        "year_range": reversed(range(1900, datetime.date.today().year + 1)),
        "day_range": range(1, 32),
        "months": [
            "Jan", "Feb", "Mar", "Apr",
            "May", "Jun", "Jul", "Aug",
            "Sep", "Oct", "Nov", "Dec"
        ],
        "hospitals": Hospital.objects.all(),
        "groups": Group.objects.all(),
        "sexes": MedicalInformation.SEX_CHOICES,
        "user_sex_other": (user and user.medical_information and
            user.medical_information.sex not in MedicalInformation.SEX_CHOICES)
    }

@login_required
def add_group(request):
    message = None
    if request.POST:
        group, message = handle_add_group_form(request, request.POST)
        if group:
            addition(request, group)
            return redirect('health:conversation', group.pk)
    return messages(request, error=message)


def handle_add_group_form(request, body):
    name = body.get('name')
    recipient_ids = body.getlist('recipient')
    message = body.get('message')

    if not all([name, recipient_ids, message]):
        return None, "All fields are required."
    if not [r for r in recipient_ids if r.isdigit()]:
        return None, "Invalid recipient."
    group = MessageGroup.objects.create(
        name=name
    )
    try:
        ids = [int(r) for r in recipient_ids]
        recipients = User.objects.filter(pk__in=ids)
    except User.DoesNotExist:
        return None, "Could not find user."
    group.members.add(request.user)
    for r in recipients:
        group.members.add(r)
    group.save()
    Message.objects.create(sender=request.user, body=message,
                           group=group, date=timezone.now())
    return group, None

@login_required
def my_medical_information(request):
    """
    Gets the primary key of the current user and redirects to the medical_information view
    for the logged-in user.
    :param request:
    :return:
    """
    return medical_information(request, request.user.pk)


@login_required
def medical_information(request, user_id):
    """
    Checks if the logged-in user has permission to modify the requested user.
    If not, raises a PermissionDenied which Django catches by redirecting to
    a 403 page.

    If requested via GET:
        Renders a page containing all the user's fields pre-filled-in
        with their information.
    If requested via POST:
        modifies the values and redirects to the same page, with the new values.
    :param request: The Django request.
    :param user_id: The user id being requested. This is part of the URL:
    /users/<user_id>/
    :return:
    """
    requested_user = get_object_or_404(User, pk=user_id)
    is_editing_own_medical_information = requested_user == request.user
    if not is_editing_own_medical_information and not\
            request.user.can_edit_user(requested_user):
        raise PermissionDenied

    context = full_signup_context(requested_user)

    if request.POST:
        user, message = handle_user_form(request, request.POST, user=requested_user)
        if user:
            return redirect('health:medical_information', user.pk)
        elif message:
            context['error_message'] = message

    context["requested_user"] = requested_user
    context["user"] = request.user
    context["requested_hospital"] = requested_user.hospital()
    context['is_signup'] = False

HealthNet/health/templates/appointment_table.html
<thead>
<tr>
    <th>Patient</th>
    <th>Doctor</th>
    <th>Date</th>
    <th>Duration</th>
    {% if editable %}
        <th>Edit</th>
        <th>Cancel</th>
    {% endif %}
</tr>
</thead>
<tbody>
{% for appointment in schedule %}
    <tr>
        <td>{% include 'user_link.html' with user=appointment.patient %}</td>
        <td>{% include 'user_link.html' with user=appointment.doctor %}</td>
        <td>{{ appointment.date }}</td>
        <td>{{ appointment.duration }} minutes</td>
        {% if editable %}
            <td><p title="Edit"><button class="btn btn-primary btn-xs" data-title="Edit" data-remote="{% url 'health:edit_appointment' appointment.pk %}" data-toggle="modal" data-target="#edit" ><span class="glyphicon glyphicon-pencil"></span></button></p></td>
            <td><p title="Delete"><a class="btn btn-danger btn-xs" data-title="Delete" href="{% url 'health:delete_appointment' appointment.pk %}"><span class="glyphicon glyphicon-trash"></span></a></p></td>
        {% endif %}
    </tr>
{% endfor %}
</tbody>

HealthNet/health/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'flatly.css' %}">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <title>HMS | {% block title %}{% endblock %}</title>
    {% block extra %}
    {% endblock %}
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container">
        {% block content %}
        <div class="text-center">
            <h1>Welcome to <strong>Virtual Hospitals</strong>, {{ user.get_full_name }}</h1>
        </div>
        {% endblock %}
    </div>
</body>
</html>

HealthNet/health/templates/conversation.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block extra %}
    <link rel="stylesheet" href="{% static 'messages.css' %}">
{% endblock %}

{% block title %}{{ message_names }}{% endblock %}

{% block content %}
    <a class="btn btn-primary" href="{% url 'health:messages' %}"><i class="fa fa-chevron-left"></i>&nbsp;Back</a>
    <h4>{{ group.name }}</h4>
    <div class="list-group">
        {% for message in group.messages.all %}
            <div class="list-group-item {% if message.sender == user %}your-message{% endif %}">
                <div class="message-content">
                    <div class="row">
                        <strong>{{ message.sender.get_full_name }}</strong>
                        <span class="badge date-badge">{{ message.date }}</span>
                    </div>
                    <br />
                    <div class="row">
                        {{ message.body|linebreaks }}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <form action="" method="post" accept-charset="utf-8" class="">
        {% csrf_token %}
        <label for="message">New Message</label>
        <textarea id="message" class="form-control" name="message"></textarea>
        <button type="submit" class="btn btn-primary">Send</button>
    </form>
{% endblock %}

HealthNet/health/templates/edit_prescription.html
<form action="{% url 'health:edit_prescription' prescription.pk %}" method="post" accept-charset="utf-8" class="form" role="form">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="add-prescription">Add a Prescription</h4>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-sm-6">
                <legend>Name</legend>
                <input class="form-control" name="name" placeholder="Ibuprofen"  {% if prescription %}value="{{ prescription.name }}" {% endif %}/>
            </div>
            <div class="col-sm-6">
                <legend>Dosage</legend>
                <input class="form-control" name="dosage" placeholder="30"  {% if prescription %}value="{{ prescription.dosage }}" {% endif %}/>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <legend>Directions</legend>
                <input class="form-control" name="directions" placeholder="Take twice a day while symptoms persist." {% if prescription %}value="{{ prescription.directions }}" {% endif %}/>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                <legend>Patient</legend>
                <select name="patient" class='form-control'>
                    {% for patient in user.active_patients %}
                        <option value="{{ patient.pk }}" {% if prescription.patient == patient %}selected="selected"{% endif %}>{{ patient.get_full_name }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button class="btn btn-primary" type="submit">Save</button>
    </div>
</form>

HealthNet/health/templates/medical_information.html
{% extends 'base.html' %}

{% block title %}{{ requested_user.get_full_name }}'s Medical Information{% endblock %}

{% block content %}
    {% if user.is_superuser or requested_user.is_patient %}
        <div class="modal fade" id="privacy" tabindex="-1" role="dialog" aria-labelledby="privacy" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        Warning
                    </div>
                    <div class="modal-body">
                        This information is potentially sensitive, and Health<strong>Net</strong> assumes no liability for privacy breaches resulting from misuse of this exported data.
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-default close-modal">
                            Cancel
                        </button>
                        <a class="btn btn-primary close-modal" href="{% url 'health:export' requested_user.pk %}" >
                            Okay
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <script>
            // close the modal on click for any button with class close-modal
            $('.close-modal').click(function(){
                $($(this).closest('.modal')).modal('hide');
            })
        </script>
    {% endif %}
    {% include 'edit_user.html' %}
    <button class="btn btn-primary" data-toggle="modal" data-target="#privacy">
        Export
    </button>
    <p>
{% endblock %}

HealthNet/health/templates/messages.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block extra %}
    <link rel="stylesheet" href="{% static 'messages.css' %}">
    <link rel="stylesheet" href="{% static 'multiselect.css' %}">
    <script src="{% static 'multiselect.js' %}"></script>
{% endblock %}

{% block title %}Messages{% endblock %}

{% block content %}
    <div class="modal fade" id="send" tabindex="-1" role="dialog" aria-labelledby="send" aria-hidden="true">
        <div class="modal-dialog">
            <form action="{% url 'health:add_group' %}" method="post" accept-charset="utf-8" class="form" role="form">
                {% csrf_token %}
                <div class="modal-content">
                    <div class="modal-header">
                        Send Message
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12">
                                    <label for="name">Conversation Name</label>
                                    <input id="name" type="text" class="form-control" name="name" placeholder="Discussion about Test Results">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="recipient">Recipient</label>
                                    <select multiple="multiple" id="recipient" name="recipient" class='form-control'>
                                        {% for user in recipients %}
                                            <option name="recipient" value="{{ user.pk }}">{{ user.get_full_name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <label for="message">Message</label>
                                    <textarea class='form-control' name="message" placeholder="Dear Doctor, I have a question..."></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" data-dismiss="send" class="btn btn-default" onclick="close_modal()">
                            Cancel
                        </button>
                        <button type="submit" class="btn btn-primary close-modal">
                            Send
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    {% include 'error.html' %}
    <button class="btn btn-primary bottom-padded" data-toggle="modal" data-target="#send">
        Send Message
    </button>
    <hr />
    <div class="list-group">
        {% if groups %}
            {% for group in groups %}
                <a href="{% url 'health:conversation' group.pk %}" class="list-group-item">
                    <div class="indent">
                        {% if group.latest_message %}
                            <span class="badge date-badge">{{ group.latest_message.date }}</span>
                        {% endif %}
                        {% if group.has_unread %}<strong>{% endif %}
                        <span class="name">
                            {{ group.combined_names }}
                        </span>
                        - <em>{{ group.name }}</em>
                        {% if group.has_unread %}</strong>{% endif %}
                    </div>
                    <div class="indent">
                        {% if group.latest_message %}
                            <span class="text-preview"><em>{% if group.latest_message.sender == user %}You: {% endif %}{{ group.latest_message.preview_text }}</em></span>
                        {% else %}
                            <span class="text-preview"><em>No Messages</em></span>
                        {% endif %}
                    </div>
                </a>
            {% endfor %}
        {% else %}
            <h2 style="text-align: center">No messages.</h2>
        {% endif %}
        <hr />
        <script>
            $('#recipient').multiselect();

            function close_modal() {
                $('#send').modal('hide');
            }
        </script>
    </div>
{% endblock %}

HealthNet/health/templates/navbar.html
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'health:home' %}"><strong>Virtal Hospitals</strong></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                    <li class="{% ifequal navbar 'home'%}active{% endifequal %}"><a href="{% url 'health:home' %}"><i class="fa fa-home"></i>&nbsp;Home</a></li>
                    <li class="{% ifequal navbar 'schedule'%}active{% endifequal %}"><a href="{% ifequal navbar 'schedule'%}#{% else %}{% url 'health:schedule' %}{% endifequal %}"><i class="fa fa-calendar"></i>&nbsp;Schedule</a></li>
                    {% if not user.is_patient or user.is_superuser %}
                        <li class="{% ifequal navbar 'prescriptions'%}active{% endifequal %}"><a href="{% ifequal navbar 'prescriptions'%}#{% else %}{% url 'health:prescriptions' %}{% endifequal %}"><i class="fa fa-medkit"></i>&nbsp;Prescriptions</a></li>
                    {% endif %}
                    {% if not user.is_superuser %}
                        <li class="{% ifequal navbar 'my_medical_information'%}active{% endifequal %}"><a href="{% ifequal navbar 'my_medical_information'%}#{% else %}{% url 'health:my_medical_information' %}{% endifequal %}"><i class="fa fa-heart"></i>&nbsp;Medical Information</a></li>
                    {% endif %}
                    <li class="{% ifequal navbar 'messages'%}active{% endifequal %}"><a href="{% ifequal navbar 'messages'%}#{% else %}{% url 'health:messages' %}{% endifequal %}"><i class="fa fa-envelope"></i>&nbsp;Messages{% if user.unread_message_count > 0 %}<span style="margin-left: 5px;" class="badge">{{ user.unread_message_count }}</span>{% endif %}</a></li>
                    {% if user.is_superuser %}
                        <li class="{% ifequal navbar 'logs'%}active{% endifequal %}"><a href="{% ifequal navbar 'logs'%}#{% else %}{% url 'health:logs' %}{% endifequal %}"><i class="fa fa-list"></i>&nbsp;System</a></li>
                        <li class="{% ifequal navbar 'users'%}active{% endifequal %}"><a href="{% ifequal navbar 'users'%}#{% else %}{% url 'health:users' %}{% endifequal %}"><i class="fa fa-user"></i>&nbsp;Users</a></li>
                    {% endif %}
                {% endif %}
            </ul>
            {% if user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    <li><p class="navbar-text">{{ user.get_full_name }}</p></li>
                    <li><a href="{% url 'health:logout' %}"><i class="fa fa-sign-out"></i>&nbsp;Sign Out</a></li>
                </ul>
            {% elif navbar != 'login' %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'health:login' %}"><i class="fa fa-sign-in"></i>&nbsp;Sign In</a></li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>

HealthNet/health/templates/prescriptions.html
{% extends 'base.html' %}
{% block title %}Prescriptions{% endblock %}
{% block content %}
    {% include 'error.html' %}
    {% if user.active_patients %}
        <div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                </div>
            </div>
        </div>
        <div class="table-responsive">
            {% if logged_in_user.can_add_prescription %}
                <button class="btn btn-primary" data-toggle="modal" data-target="#edit" data-remote="{% url 'health:add_prescription' %}">Add a Prescription</button>
                <hr />
                {% for user in user.active_patients %}
                    {% if user.active_prescriptions %}
                        <table class="table table-bordered table-striped">
                            <legend>Prescriptions for {% include 'user_link.html' %}</legend>
                            <thead>
                            <tr>
                                <th>Dosage</th>
                                <th>Name</th>
                                <th>Directions</th>
                                {% if logged_in_user.can_add_prescription %}
                                    <th>Edit</th>
                                    <th>Delete</th>
                                {% endif %}
                            </tr>
                            </thead>
                            <tbody>
                            {% for prescription in user.active_prescriptions %}
                                <tr>
                                    <td>{{ prescription.dosage }}</td>
                                    <td>{{ prescription.name }}</td>
                                    <td>{{ prescription.directions }}</td>

                                    {% if logged_in_user.can_add_prescription %}
                                        <td><p title="Edit"><button class="btn btn-primary btn-xs" data-title="Edit" data-remote="{% url 'health:edit_prescription' prescription.pk %}" data-toggle="modal" data-target="#edit"><span class="glyphicon glyphicon-pencil"></span></button></p></td>
                                        <td><p title="Delete"><a class="btn btn-danger btn-xs" data-title="Delete" href="{% url 'health:delete_prescription' prescription.pk %}"><span class="glyphicon glyphicon-trash"></span></a></p></td>
                                    {% endif %}

                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <div class="text-center">
                            <h2> No prescriptions for {% include 'user_link.html' %}</h2>
                        </div>
                    {% endif %}
                    <hr />
                {% endfor %}
            {% endif %}
        </div>
    {% else %}
        <h2 class="text-center"> No active patients in hospital. </h2>
    {% endif %}
    <script>
        // Remove the data from the modal when it's closed.
        $(document).on('hidden.bs.modal', function (e) {
            $(e.target).removeData('bs.modal');
        });
    </script>
{% endblock %}

HealthNet/health/templates/user_link.html
<a href="{% url 'health:medical_information' user.pk %}">{{ user.get_full_name }}</a>